public class Campaign
{
    public string? Children { get; set; }
    public string? CompanyAddress { get; set; }
    public string? CompanyCity { get; set; }
    public string? CompanyDescription { get; set; }
    public string? CompanyDomain { get; set; }
    public string? CompanyEmployeeCount { get; set; }
    public string? CompanyLastUpdated { get; set; }
    public string? CompanyLinkedInUrl { get; set; }
    public string? CompanyNaics { get; set; }
    public string? CompanyName { get; set; }
    public string? CompanyPhone { get; set; }
    public string? CompanyRevenue { get; set; }
    public string? CompanySic { get; set; }
    public string? CompanyState { get; set; }
    public string? CompanyZip { get; set; }
    public string? CreatedAt { get; set; }
    public string? Department { get; set; }
    public string? DirectNumber { get; set; }
    public string? DpvCode { get; set; }
    public string? EducationHistory { get; set; }
    public string? FirstName { get; set; }
    public string? Gender { get; set; }
    public string? Homeowner { get; set; }
    public string? IncomeRange { get; set; }
    public string? JobTitle { get; set; }
    public string? JobTitleLastUpdated { get; set; }
    public string? LastName { get; set; }
    public string? LastUpdated { get; set; }
    public string? LinkedInUrl { get; set; }
    public string? Married { get; set; }
    public string? MobilePhone { get; set; }
    public string? NetWorth { get; set; }
    public string? PersonalAddress { get; set; }
    public string? PersonalAddress2 { get; set; }
    public string? PersonalCity { get; set; }
    public string? PersonalEmails { get; set; }
    public string? PersonalEmailsLastSeen { get; set; }
    public string? PersonalEmailsValidationStatus { get; set; }
    public string? PersonalPhone { get; set; }
    public string? PersonalState { get; set; }
    public string? PersonalZip { get; set; }
    public string? PersonalZip4 { get; set; }
    public string? PrimaryIndustry { get; set; }
    public string? ProfessionalAddress { get; set; }
    public string? ProfessionalAddress2 { get; set; }
    public string? ProfessionalCity { get; set; }
    public string? ProfessionalState { get; set; }
    public string? ProfessionalZip { get; set; }
    public string? ProfessionalZip4 { get; set; }
    public string? ProgrammaticBusinessEmails { get; set; }
    public string? RelatedDomains { get; set; }
    public string? SeniorityLevel { get; set; }
    public string? SocialConnections { get; set; }
    public string? SubCategory { get; set; }
    public string? Topic { get; set; }
    public string? UpId { get; set; }
    public string? WorkHistory { get; set; }
    public string? Score { get; set; }
    public string? Sha256LcHem { get; set; }
}
